#!/usr/bin/env bash
# GraderUP — one-shot VPS install (Ubuntu 22.04/24.04 or Debian 12), run as root from the repo root:
#   bash deploy/setup-vps.sh            # uses defaults below
#   PUBLIC_HOST=1.2.3.4 PORT=4555 bash deploy/setup-vps.sh
# Installs Docker, writes .env.production with generated secrets (only if missing),
# builds and starts PostgreSQL + app + nginx (port $PORT) and seeds the catalogue.
set -euo pipefail

PUBLIC_HOST="${PUBLIC_HOST:-45.131.186.197}"
PORT="${PORT:-4555}"
cd "$(dirname "$0")/.."

if [ "$(id -u)" -ne 0 ]; then echo "Запусти от root: sudo bash deploy/setup-vps.sh"; exit 1; fi

echo "==> 1/6 Docker"
if ! command -v docker >/dev/null 2>&1; then
  curl -fsSL https://get.docker.com | sh
fi
systemctl enable --now docker >/dev/null 2>&1 || true

echo "==> 2/6 Swap (next build needs ~2 GB RAM)"
if [ "$(free -m | awk '/^Mem:/{print $2}')" -lt 3000 ] && ! swapon --show | grep -q .; then
  fallocate -l 2G /swapfile && chmod 600 /swapfile && mkswap /swapfile >/dev/null && swapon /swapfile
  grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
fi

echo "==> 3/6 .env.production"
if [ ! -f .env.production ]; then
  ADMIN_PASS="$(openssl rand -base64 12 | tr -dc 'A-Za-z0-9' | head -c 14)Aa1!"
  cat > .env.production <<EOF
# Generated by deploy/setup-vps.sh — keep this file private (it is gitignored).
PORT=${PORT}
APP_URL=http://${PUBLIC_HOST}:${PORT}
APP_NAME=GraderUP
POSTGRES_PASSWORD=$(openssl rand -hex 24)
SESSION_SECRET=$(openssl rand -hex 32)
PAYMENT_SECRET=$(openssl rand -hex 32)
# Payments: real providers turn on when their keys are set (see .env.example).
PAYMENT_PROVIDER=mock
ALLOW_MOCK_PAYMENTS_IN_PRODUCTION=false
PALLY_API_TOKEN=
PALLY_SHOP_ID=
ANYPAY_MERCHANT_ID=
ANYPAY_SECRET_KEY=
XROCKET_API_KEY=

# Skin withdrawals to Steam: marketcsgo = real delivery via market.csgo.com buy-for (needs key + funded market balance).
TRADE_PROVIDER=none
ALLOW_MOCK_TRADES_IN_PRODUCTION=false
MARKETCSGO_API_KEY=
MARKETCSGO_MAX_OVERPAY_PERCENT=10

STEAM_AUTH_ENABLED=true
STEAM_API_KEY=
EMAIL_REGISTRATION_ENABLED=false

# Seed (first start only)
SEED_DEMO=false
SEED_ADMIN_EMAIL=admin@graderup.local
SEED_ADMIN_PASSWORD=${ADMIN_PASS}
EOF
  chmod 600 .env.production
  echo "    создан .env.production"
else
  echo "    .env.production уже есть — не трогаю"
fi

COMPOSE="docker compose -f docker-compose.prod.yml --env-file .env.production"

echo "==> 4/6 Build & start (первый раз 3–8 минут)"
$COMPOSE up -d --build

echo "==> 5/6 Seed (CS2 skins + cases, only on an empty database)"
for i in $(seq 1 30); do
  $COMPOSE exec -T app node -e "fetch('http://127.0.0.1:'+process.env.PORT+'/robots.txt').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))" && break
  sleep 3
done
$COMPOSE exec -T app npm run db:seed

echo "==> 6/6 Firewall"
# Docker publishes the port itself; if ufw is active, also add an explicit rule for clarity.
if command -v ufw >/dev/null 2>&1 && ufw status | grep -q 'Status: active'; then
  ufw allow "${PORT}/tcp" >/dev/null
fi

echo
echo "Готово: http://${PUBLIC_HOST}:${PORT}"
echo "Админка: http://${PUBLIC_HOST}:${PORT}/cmsadmin"
grep -E '^SEED_ADMIN_(EMAIL|PASSWORD)=' .env.production
