#!/usr/bin/env bash
# GraderUP TEST server (next to the live one): bash deploy/setup-test.sh
# Own DB/cookies, port 4556, "Тестовый сервер" banner, noindex, mock payments/trades, bots always on.
set -euo pipefail
PUBLIC_HOST="${PUBLIC_HOST:-45.131.186.197}"
PORT="${PORT:-4556}"
cd "$(dirname "$0")/.."
if [ "$(id -u)" -ne 0 ]; then echo "Запусти от root"; exit 1; fi
command -v docker >/dev/null 2>&1 || curl -fsSL https://get.docker.com | sh

if [ ! -f .env.test-server ]; then
  cat > .env.test-server <<ENV
# TEST server — generated by deploy/setup-test.sh (gitignored).
PORT=${PORT}
APP_URL=http://${PUBLIC_HOST}:${PORT}
APP_NAME=GraderUP TEST
SITE_MODE=test
POSTGRES_PASSWORD=$(openssl rand -hex 24)
SESSION_SECRET=$(openssl rand -hex 32)
PAYMENT_SECRET=$(openssl rand -hex 32)
PAYMENT_PROVIDER=mock
ALLOW_MOCK_PAYMENTS_IN_PRODUCTION=true
TRADE_PROVIDER=mock
ALLOW_MOCK_TRADES_IN_PRODUCTION=true
STEAM_AUTH_ENABLED=true
SEED_DEMO=true
SEED_ADMIN_EMAIL=admin@graderup.local
SEED_ADMIN_PASSWORD=$(openssl rand -base64 12 | tr -dc 'A-Za-z0-9' | head -c 12)Aa1!
SIM_BOTS=40
SIM_INTERVAL=2
ENV
  chmod 600 .env.test-server
fi

C="docker compose -f docker-compose.test.yml --env-file .env.test-server"
$C up -d --build db app nginx
for i in $(seq 1 30); do
  $C exec -T app node -e "fetch('http://127.0.0.1:3000/robots.txt').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))" && break
  sleep 3
done
$C exec -T app npm run db:seed
$C up -d sim
if command -v ufw >/dev/null 2>&1 && ufw status | grep -q 'Status: active'; then ufw allow "${PORT}/tcp" >/dev/null; fi

echo
echo "Тестовый сервер: http://${PUBLIC_HOST}:${PORT}   (админка: /cmsadmin)"
grep -E '^SEED_ADMIN_(EMAIL|PASSWORD)=' .env.test-server
echo "Боты: $C logs -f sim   | остановить ботов: $C stop sim"
